"""Tier 0: constants.py must equal the Fortran source, value for value.

Parses the vendored ``qtcmpar.F90`` / ``qtcmmod.F90`` (verbatim copies from
QTCM1 v2.3 as shipped in qtcm 0.1.2) and compares every transcribed scalar
and table. Float32 sources are compared at float32 resolution.
"""

import os
import re

import numpy as np
import pytest

from qtcm1 import constants

DATA = os.path.join(os.path.dirname(__file__), 'data')
_FLOAT = r'[+-]?(?:\d+\.?\d*|\.\d+)(?:[eEdD][+-]?\d+)?'


def _to_float(tok: str) -> float:
    return float(tok.replace('d', 'e').replace('D', 'E'))


def _parse_assignments(src: str) -> dict[str, float]:
    """Extract ``name = <float>`` parameter assignments from Fortran source."""
    out = {}
    for m in re.finditer(rf'(\w+)\s*=\s*({_FLOAT})\s*[,&!\n]', src):
        name, val = m.group(1), m.group(2)
        try:
            out[name] = _to_float(val)
        except ValueError:  # pragma: no cover
            pass
    return out


def _floats_between(src: str, start: str, end: str) -> np.ndarray:
    """All float literals between two source markers."""
    seg = src.split(start, 1)[1].split(end, 1)[0]
    seg = re.sub(r'!.*', '', seg)                     # strip comments
    return np.array([_to_float(t) for t in re.findall(_FLOAT, seg)])


@pytest.fixture(scope='module')
def fortran_values():
    src_par = open(os.path.join(DATA, 'qtcmpar.F90')).read()
    src_mod = open(os.path.join(DATA, 'qtcmmod.F90')).read()
    vals = _parse_assignments(src_mod)
    vals.update(_parse_assignments(src_par))
    return vals, src_par


def test_scalars_match_fortran(fortran_values):
    vals, _ = fortran_values
    missing = [k for k in constants.FORTRAN_NAME_MAP if k not in vals]
    assert not missing, f'not found in Fortran source: {missing}'
    for name, pyval in constants.FORTRAN_NAME_MAP.items():
        fval = vals[name]
        assert np.float32(pyval) == np.float32(fval), \
            f'{name}: python {pyval!r} != fortran {fval!r}'


def test_v1z_table(fortran_values):
    _, src = fortran_values
    flat = _floats_between(src, 'V1z1d= &', '#ifdef TOPO')
    table = flat[:2 * constants.NZ_TABLE].reshape(constants.NZ_TABLE, 2)
    np.testing.assert_array_equal(np.float32(constants.V1Z_TABLE),
                                  np.float32(table))


def test_t1c_table(fortran_values):
    _, src = fortran_values
    flat = _floats_between(src, 'table= &', 'End Module T1cTableIn')
    table = flat[:4 * 11].reshape(11, 4)
    np.testing.assert_array_equal(np.float32(constants.T1C_TABLE),
                                  np.float32(table))


def test_advection_coefficient_tables(fortran_values):
    _, src = fortran_values
    vijkt = _floats_between(src, 'Vijkt = (/', '/)')
    np.testing.assert_array_equal(np.float32(constants.VIJKT),
                                  np.float32(vijkt[:8]))
    vwijkt = _floats_between(src, 'Vwijkt = (/', '/)')
    np.testing.assert_array_equal(np.float32(constants.VWIJKT),
                                  np.float32(vwijkt[:8]))
    dtijkt = _floats_between(src, 'DTijkt = (/', '/)')
    np.testing.assert_array_equal(np.float32(constants.DTIJKT),
                                  np.float32(dtijkt[:2]))
    dqijkt = _floats_between(src, 'Dqijkt = (/', '/)')
    np.testing.assert_array_equal(np.float32(constants.DQIJKT),
                                  np.float32(dqijkt[:2]))


def test_derived_relations():
    """Internal consistency: relations the formulation guarantees."""
    assert constants.V1S == -constants.A1PHAT          # NZ (3.10) at surface
    assert constants.GPTI == constants.GRAVITY / constants.DELP
    # Cpg's implied pressure depth is ~850 hPa, NOT the nominal DELP=800:
    # generated by the offline `par` program with the actual troposphere
    # depth. Pin this as intentional so nobody "fixes" it silently.
    implied_delp = constants.CPG * constants.GRAVITY / constants.CP
    assert np.isclose(implied_delp, 85000.0, rtol=1e-3)
    assert not np.isclose(implied_delp, constants.DELP, rtol=1e-2)
    # a1 at surface in the T1c table equals a1s
    assert np.float32(constants.T1C_TABLE[0, 3]) == np.float32(constants.A1S)
