"""The dynamic effect of topography (the TOPO option).

``RunConfig(topo=True)`` activates what the Fortran ``-DTOPO`` build
activates: the divergence generated by topographic lifting,
div0 = v_s . grad(TOP) with terrain-following surface winds, drives a
vortex-stretching term -f*div0 in the barotropic vorticity equation and
enters the omega-advection terms. The source's own note: "improves
northern hemisphere rainfall and flow pattern significantly".

Two otherwise identical one-year runs (TOPO on / off) and the
annual-mean precipitation difference, with the topography contoured on
top - the response concentrates around the Tibetan Plateau and the
Rockies/Andes. One year is illustrative, not a climatology; run longer
(and average more years) for quantitative statements. Runtime ~4 min.
"""

import os

import matplotlib.pyplot as plt
import numpy as np

from qtcm1.config import RunConfig
from qtcm1.driver import ControlRun


def year_mean_prec(topo: bool):
    run = ControlRun(config=RunConfig(data_path=DATA, topo=topo))
    run.run_years(1, progress=lambda d, date: print(f'day {d}', end='\r'))
    qc = np.mean([m['Qc'] for _, _, m in run.monthly], axis=0)
    return qc * 86400.0 / 2.43e6, run                    # mm/day


DATA = os.environ.get('QTCM1_BNDDATA')   # None -> packaged data/r64x42

prec_off, run = year_mean_prec(False)
prec_on, _ = year_mean_prec(True)
dprec = prec_on - prec_off

lat, lon = run.bd.lat, run.bd.lon
top = np.where(run.bd.top < 0.1, 0.0, run.bd.top)        # bndinit threshold

fig, ax = plt.subplots(figsize=(8.6, 4.0))
lim = float(np.abs(dprec).max())
cf = ax.contourf(lon, lat, dprec, levels=np.linspace(-lim, lim, 17),
                 cmap='RdBu_r')
cs = ax.contour(lon, lat, top, levels=[0.1, 0.2, 0.3, 0.4, 0.5],
                colors='k', linewidths=0.7)
ax.contour(lon, lat, (run.model.stype > 0).astype(float), levels=[0.5],
           colors='0.45', linewidths=0.6)
ax.set_title('annual-mean precipitation: TOPO on minus off (year 1)')
ax.set_xlabel('longitude [degrees east]')
ax.set_ylabel('latitude [degrees north]')
fig.colorbar(cf, ax=ax, label=r'$\Delta$ precipitation [mm day$^{-1}$]')
fig.tight_layout()
fig.savefig('topo_precip_effect.png', dpi=150)
print('\nwrote topo_precip_effect.png')
