"""Physical constants and QTCM1 mode parameters.

Ported verbatim from ``PhysicalConstants`` (qtcmmod.F90) and module
``Qtcmpar`` + ``T1cTableIn`` (qtcmpar.F90) of QTCM1 v2.3. Values are
transcribed, not recomputed; ``tests/test_constants.py`` (Tier 0) parses the
vendored Fortran source and asserts equality, so transcription errors cannot
survive CI.

Notation follows Neelin & Zeng (2000) [NZ]; each entry cites its NZ equation
where the Fortran does.
"""

from __future__ import annotations

import numpy as np

# --------------------------------------------------------------------------
# Module PhysicalConstants (qtcmmod.F90)
# --------------------------------------------------------------------------
REARTH = 6.37e6          #: Earth radius [m]
RHOAIR = 1.20            #: air density [kg m-3]
RAIR = 287.040           #: gas constant, air [J kg-1 K-1]
OMEGA = 7.292e-5         #: Earth angular velocity [s-1]
HLATENT = 2.43e6         #: latent heat [J kg-1] (model value, not 2.5e6)
CP = 1.004e3             #: heat capacity at constant pressure [J kg-1 K-1]
GRAVITY = 9.8            #: gravitational acceleration [m s-2]
DELP = 80000.0           #: total pressure depth p_T [Pa]
GPTI = GRAVITY / DELP    #: NZ g/p_T [m s-2 Pa-1]

# --------------------------------------------------------------------------
# Module Qtcmpar (qtcmpar.F90) - mode counts and table sizes
# --------------------------------------------------------------------------
NVMOD = 2                #: number of velocity modes (V0, V1)
NTMOD = 1                #: number of temperature modes (T1)
NZ_TABLE = 14            #: V1(z) table size

# --------------------------------------------------------------------------
# Module Qtcmpar - scalar mode parameters
# --------------------------------------------------------------------------
A1HAT = 0.45934832       #: \hat{a_1} [-], NZ (3.2)
A1PHAT = 0.24527773      #: \hat{a_1^+} [-], NZ (2.16), (3.9)
A1S = 0.30203983         #: a_{1s} [-], NZ (5.16)
V1S = -0.24527773        #: V_{1s} [-], NZ (4.13)
V1SQHAT = 0.39477620e-01  #: \hat{V_1^2} [-], NZ (4.13)
B1HAT = 0.31574178       #: \hat{b_1} [-], NZ (5.17)
B1S = 1.0000000          #: b_{1s} [-], NZ (4.32)
BB1HAT = 0.37340331      #: \hat{B_1} [-], NZ (4.26)
GMSR = 3.5999999         #: M_{sr} [K], NZ (4.17)
GMSP = 0.42701162e-01    #: M_{sp} [-], NZ (4.18)
GMQR = 3.0000000         #: M_{qr} [K], NZ (5.10)
GMQP = 0.50709546e-01    #: M_{qp} [-], NZ (5.10)
EPS_I1 = 0.89938197e-06  #: mode-1 vertical-diffusion rate [s-1] (~13 day)
TSREF = 302.26001        #: reference Ts for radiation [K]
#: Column heat capacity "Cp*delp/gravity" [J K-1 m-2]. NB: the tabulated
#: value implies a pressure depth of ~850 hPa (8708163*9.8/1004), NOT the
#: nominal DELP = 800 hPa -- Cpg was generated by the offline ``par`` program
#: with the actual troposphere depth. Both constants are used as-is where the
#: Fortran uses them; do not "fix" one to match the other.
CPG = 8708163.0
TREFS = 302.00000        #: surface T reference [K]
QREFS = 51.955288        #: surface q reference [K]
TCREFS = 302.00000       #: convective surface T reference [K]
QCREFS = 50.814919       #: convective surface q reference [K]
TREFHAT = 267.77045      #: column-mean reference temperature [K]
QREFHAT = 16.404453      #: column-mean reference humidity [K]
TCREFHAT = 268.98318     #: convective column-mean reference temperature [K]
QCREFHAT = 16.159273     #: convective column-mean reference humidity [K]

#: Convective adjustment rate 1/tau_c [s-1], NZ (5.7). A *runtime parameter*
#: in the wrapped model (Fortran default read from qtcm.py defaults);
#: tau_c = 2 h.
EPS_C_DEFAULT = 1.0 / 7200.0

# --------------------------------------------------------------------------
# Module Qtcmpar - advection projection coefficients, NZ (4.8)-(4.9)
# Vijkt/Vwijkt are <V_i V_j>/<V_k^2>-type inner products packed exactly as in
# the Fortran DATA statements (index order (:, j, k) flattened Fortran-style).
# --------------------------------------------------------------------------
VIJKT = np.array([
    1.0000000, 0.0000000,        # Vijk(:,0,0)
    0.0000000, 0.39477620e-01,   # Vijk(:,1,0)
    0.0000000, 1.0000000,        # Vijk(:,0,1)
    1.0000000, 0.11037793,       # Vijk(:,1,1)
])

VWIJKT = np.array([
    0.0000000, 0.0000000,        # Vwijk(:,0,0)
    0.24527763, 0.39408989e-01,  # Vwijk(:,1,0)
    0.0000000, 0.0000000,        # Vwijk(:,0,1)
    -0.26465219, 0.54747105e-01,  # Vwijk(:,1,1)
])

DTIJKT = np.array([1.0000000, 0.68389595e-01])   # DTijk(:,1,1)
DQIJKT = np.array([1.0000000, -0.16060449])      # Dqijk(:,1,1)

# --------------------------------------------------------------------------
# Module Qtcmpar - V1(z) profile table (z [m], V1 [-]); nz=14 rows
# --------------------------------------------------------------------------
V1Z_TABLE = np.array([
    [0.0000000, -0.24527773],
    [200.00000, -0.23844716],
    [400.00000, -0.23163342],
    [600.00000, -0.22483708],
    [800.00000, -0.21805863],
    [1000.0000, -0.21128868],
    [2000.0000, -0.17567538],
    [3000.0000, -0.13634732],
    [4000.0000, -0.92545077e-01],
    [5000.0000, -0.43332372e-01],
    [6000.0000, 0.12398618e-01],
    [7000.0000, 0.76425947e-01],
    [8000.0000, 0.15042150],
    [9000.0000, 0.23544320],
])

# --------------------------------------------------------------------------
# Module T1cTableIn (qtcmpar.F90) - nonlinear T1c closure profile table
# columns: p [hPa], alpha [-], Tsat [K], a1 [-]; np=11 rows
# --------------------------------------------------------------------------
T1C_TABLE = np.array([
    [1000.0000, 0.85000002, 302.00000, 0.30203983],
    [950.00000, 0.83529413, 297.64838, 0.29764509],
    [900.00000, 0.82058823, 293.08527, 0.29308203],
    [850.00000, 0.80588239, 291.01846, 0.30323407],
    [800.00000, 0.79117650, 288.79773, 0.31495297],
    [700.00000, 0.76176476, 283.78235, 0.34451482],
    [600.00000, 0.73235297, 277.72491, 0.38630155],
    [500.00000, 0.70294118, 270.06317, 0.44864291],
    [400.00000, 0.67352945, 259.69208, 0.54513770],
    [300.00000, 0.64411765, 244.30972, 0.67801291],
    [200.00000, 0.61470592, 219.90630, 0.74564552],
])

#: Map from Fortran constant name (qtcmpar.F90 / qtcmmod.F90) to the value
#: defined here - consumed by the Tier-0 checker.
FORTRAN_NAME_MAP = {
    'Rearth': REARTH, 'rhoair': RHOAIR, 'Rair': RAIR, 'Omega': OMEGA,
    'Hlatent': HLATENT, 'Cp': CP, 'gravity': GRAVITY, 'delp': DELP,
    'a1hat': A1HAT, 'a1phat': A1PHAT, 'a1s': A1S, 'V1s': V1S,
    'V1sqhat': V1SQHAT, 'b1hat': B1HAT, 'b1s': B1S, 'bb1hat': BB1HAT,
    'GMsr': GMSR, 'GMsp': GMSP, 'GMqr': GMQR, 'GMqp': GMQP,
    'eps_i1': EPS_I1, 'Tsref': TSREF, 'Cpg': CPG, 'Trefs': TREFS,
    'qrefs': QREFS, 'Tcrefs': TCREFS, 'qcrefs': QCREFS,
    'Trefhat': TREFHAT, 'qrefhat': QREFHAT, 'Tcrefhat': TCREFHAT,
    'qcrefhat': QCREFHAT,
}
